In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [3]:
read_file = pd.read_excel ("trombosit.xlsx")

In [4]:
read_file.to_csv ("trombosit.csv",  
                  index = None, 
                  header=True) 

In [5]:
df = pd.DataFrame(pd.read_csv("trombosit.csv"))

In [6]:
df

pc   pdw   mpv  pct  stage
0    1075  12.9  12.6  0.7      4
1     950  11.9  10.9  0.6      4
2     890  11.2  10.8  0.5      4
3     874  10.9  10.7  0.5      4
4     859  10.8  10.9  0.5      4
..    ...   ...   ...  ...    ...
364   184   6.5   6.3  0.0      1
365   178   6.3   6.5  0.0      1
366   177   6.5   6.8  0.0      1
367   159   6.3   6.5  0.0      1
368   152   6.2   6.2  0.0      1

[369 rows x 5 columns]

In [7]:
platelet_dataset = pd.read_csv('trombosit.csv')

In [8]:
X = platelet_dataset.drop(columns='stage', axis=1)
Y = platelet_dataset['stage']

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(X)

StandardScaler()

In [11]:
standardized_data = scaler.transform(X)

In [12]:
print(standardized_data)

[[ 3.79375417  3.23733065  3.22177956  3.34372658]
 [ 3.03558193  2.43871118  1.78312472  2.71421887]
 [ 2.67165926  1.87967754  1.69849796  2.08471116]
 ...
 [-1.6529552  -1.87383399 -1.68657224 -1.06282738]
 [-1.762132   -2.03355788 -1.94045251 -1.06282738]
 [-1.80458965 -2.11341983 -2.19433277 -1.06282738]]


In [37]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y, random_state=2)

In [38]:
classifier = svm.SVC(kernel='linear')

In [39]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [40]:
X_train_prediction = classifier.predict(X_train)

In [41]:
X_test_prediction = classifier.predict(X_test)

In [42]:
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [43]:
print(training_data_accuracy)

0.8449612403100775


In [44]:
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(test_data_accuracy)

0.8828828828828829


In [45]:
import pickle
filename="trombositmodel.sav"
pickle.dump(classifier, open(filename,'wb'))

In [46]:
loaded_model=pickle.load(open("trombositmodel.sav",'rb'))